# Prof. Anju Mam says,
Python 1D ayyay

In [1]:
print("Hello, Word!")

Hello, Word!


# Numpy

In [2]:
import numpy as np

## 1D Array

In [3]:
# Create a NumPy array with 4 elements
arr = np.array([1, 2, 3, 4], dtype=np.int8)

# Print the elements of the array
print(arr)

[1 2 3 4]


In [4]:
# Print the data type of the variable 'arr' (NumPy ndarray)
print('line: 02', type(arr))

# Print the number of dimensions of the array (1D array)
print('line: 05', arr.ndim)

# Print the shape of the array (rows, columns)
# For a 1D array, it returns (number_of_elements)
print('line: 09', arr.shape)

line: 02 <class 'numpy.ndarray'>
line: 05 1
line: 09 (4,)


In [5]:
# Print the total number of elements in the array
print('line: 02', arr.size)

# Print the size (in bytes) of one array element
print('line: 05', arr.itemsize)

# Print the total number of bytes consumed by the array
# Total bytes = size × itemsize
print('line: 09', arr.nbytes)

line: 02 4
line: 05 1
line: 09 4


In [6]:
# Print the Type of element of array
print('line: 02', arr.dtype)

line: 02 int8


## 2D Array

In [7]:
# Create a NumPy array with 3x3 dimensions with 1 to 9
two_d_arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=np.int8)

# Print the elements of the 2D array
print(two_d_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
# Print the data type of the variable 'two_d_arr' (NumPy ndarray)
print('line: 02', type(two_d_arr))

# Print the number of dimensions of the array (2D array)
print('line: 05', two_d_arr.ndim)

# Print the shape of the array (rows, columns)
print('line: 09', two_d_arr.shape)

line: 02 <class 'numpy.ndarray'>
line: 05 2
line: 09 (3, 3)


In [9]:
# Print the total number of elements in the array
print('line: 02', two_d_arr.size)

# Print the size (in bytes) of one array element
print('line: 05', two_d_arr.itemsize)

# Print the total number of bytes consumed by the array
# Total bytes = size × itemsize
print('line: 09', two_d_arr.nbytes)

line: 02 9
line: 05 1
line: 09 9


In [10]:
# Print the Type of element of array
print('line: 02', arr.dtype)

line: 02 int8


## 3D Array

In [11]:
# Create a NumPy array with 3x3x3 dimensions with 1 to 9
three_d_arr = np.array([
    [
        [0, 1, 2],
        [3, 4, 5],
        [6, 7, 8],
    ],
    [
        [0, 1, 2],
        [3, 4, 5],
        [6, 7, 8],
    ],
    [
        [0, 1, 2],
        [3, 4, 5],
        [6, 7, 8],
    ]
])


# Print the elements of the 3D array
print(three_d_arr)

[[[0 1 2]
  [3 4 5]
  [6 7 8]]

 [[0 1 2]
  [3 4 5]
  [6 7 8]]

 [[0 1 2]
  [3 4 5]
  [6 7 8]]]


In [12]:
# Print the number of dimensions of the array (3D array)
print('line: 02', three_d_arr.ndim)

# Print the shape of the array (rows, columns, height)
print('line: 05', three_d_arr.shape)

# Print the total number of elements in the array
print('line: 08', three_d_arr.size)

# Print the size (in bytes) of one array element
print('line: 11', three_d_arr.itemsize, 'bytes')

# Print the total number of bytes consumed by the array
# Total bytes = size × itemsize
print('line: 15', three_d_arr.nbytes)

# Print the Type of element of array
print('line: 02', arr.dtype)

line: 02 3
line: 05 (3, 3, 3)
line: 08 27
line: 11 8 bytes
line: 15 216
line: 02 int8


## Random Number

In [13]:
# Create a NumPy array with 1 dimensions with random integers
random_ele_arr = np.random.randint(0, 10, 10)
print(random_ele_arr)

[4 7 0 2 5 0 1 9 9 0]


In [14]:
# Create a NumPy array with 3 dimensions with random integers
random_ele_arr = np.random.randint(0, 10, (3, 3))
print(random_ele_arr)

[[5 3 5]
 [1 2 4]
 [1 7 6]]


## Custom Matrix

In [15]:
zero_matrix = np.zeros((3, 3))
print(zero_matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [16]:
ones_matrix = np.ones((2,4))
print(ones_matrix)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [17]:
custom_matrix = np.full((5,2), 6)
print(custom_matrix)

[[6 6]
 [6 6]
 [6 6]
 [6 6]
 [6 6]]


In [18]:
identity_matrix = np.eye(4, 4, dtype='int8')
print(identity_matrix)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [19]:
print(random_ele_arr.min())
print(random_ele_arr.max())

1
7


In [20]:
print(random_ele_arr.argmin())
print(random_ele_arr.argmax())

3
7


## Arithmetic Operations on Matrix

In [21]:
arr1 = np.random.randint(0, 10, (3, 3))
print(arr1)
arr2 = np.random.randint(1, 10, (3, 3))
print(arr2)

[[8 7 8]
 [1 3 7]
 [1 4 0]]
[[1 1 8]
 [3 8 4]
 [2 6 8]]


In [22]:
np.add(arr1, arr2)

array([[ 9,  8, 16],
       [ 4, 11, 11],
       [ 3, 10,  8]], dtype=int32)

In [23]:
np.subtract(arr1, arr2)

array([[ 7,  6,  0],
       [-2, -5,  3],
       [-1, -2, -8]], dtype=int32)

In [24]:
np.multiply(arr1, arr2)

array([[ 8,  7, 64],
       [ 3, 24, 28],
       [ 2, 24,  0]], dtype=int32)

In [25]:
np.divide(arr1, arr2)

array([[8.        , 7.        , 1.        ],
       [0.33333333, 0.375     , 1.75      ],
       [0.5       , 0.66666667, 0.        ]])

In [26]:
np.cross(arr1, arr2)

array([[ 48, -56,   1],
       [-44,  17,  -1],
       [ 32,  -8,  -2]], dtype=int32)

## Array Indexing & Slicing

In [43]:
my_elements = np.random.randint(0, 10, (6, 6))
print(my_elements)

[[4 7 9 8 0 8]
 [9 7 3 5 6 2]
 [3 8 4 0 3 7]
 [5 0 6 7 6 3]
 [8 6 9 2 6 2]
 [6 4 6 8 2 1]]


In [44]:
print(my_elements[-1, 0])

6


In [45]:
print(my_elements[2:, :6:2])

[[3 4 3]
 [5 6 6]
 [8 9 6]
 [6 6 2]]


In [41]:
# my_elements[:] = 100
# print(my_elements)

[[100 100 100 100 100 100]
 [100 100 100 100 100 100]
 [100 100 100 100 100 100]
 [100 100 100 100 100 100]
 [100 100 100 100 100 100]
 [100 100 100 100 100 100]]


# Pandas